--- #YAML:1.0
name:                DBIx-StORM
version:             0.09
abstract:            Perl extension for object-relational mapping
license:             ~
author:              
    - Luke Ross <luke@lukeross.name>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    B:                             0
    Carp:                          0
    constant:                      0
    DBI:                           0
    FindBin:                       0
    overload:                      0
    Scalar::Util:                  0
    XML::XPath:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
